"""Add UserImage table

Revision ID: c1b0269f1c91
Revises: 
Create Date: 2025-09-08 16:43:58.838536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b0269f1c91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_images',
    sa.Column('id', sa.Integer(), nullable=False, comment='画像ID（主キー）'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID（外部キー）'),
    sa.Column('image_path', sa.String(length=255), nullable=False, comment='画像パス'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='ファイル名'),
    sa.Column('original_filename', sa.String(length=255), nullable=True, comment='元のファイル名'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True, comment='アップロード日時'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='有効フラグ'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='論理削除フラグ'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_images')
    # ### end Alembic commands ###
