"""Initial migration

Revision ID: fd160c6c9b0b
Revises: 
Create Date: 2025-09-09 19:53:43.891287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd160c6c9b0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='ユーザーID（主キー）'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='ユーザー名（一意）'),
    sa.Column('email', sa.String(length=120), nullable=False, comment='メールアドレス（一意）'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='パスワードハッシュ'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='アカウント有効フラグ'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, comment='管理者フラグ'),
    sa.Column('organization', sa.String(length=100), nullable=True, comment='所属'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最終ログイン日時'),
    sa.Column('access_count', sa.Integer(), nullable=True, comment='アクセス回数'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='ログイン状態'),
    sa.Column('login_attempts', sa.Integer(), nullable=True, comment='ログイン試行回数'),
    sa.Column('role', sa.String(length=20), nullable=True, comment='権限/ロール'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False, comment='住所ID（主キー）'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID（外部キー）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='宛先名'),
    sa.Column('postal_code', sa.String(length=10), nullable=True, comment='郵便番号'),
    sa.Column('prefecture', sa.String(length=20), nullable=True, comment='都道府県'),
    sa.Column('city', sa.String(length=50), nullable=True, comment='市区町村'),
    sa.Column('address_line1', sa.String(length=100), nullable=True, comment='住所1（町名・番地）'),
    sa.Column('address_line2', sa.String(length=100), nullable=True, comment='住所2（建物名・部屋番号）'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='電話番号'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='デフォルト住所フラグ'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='有効フラグ'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_images',
    sa.Column('id', sa.Integer(), nullable=False, comment='画像ID（主キー）'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID（外部キー）'),
    sa.Column('image_path', sa.String(length=255), nullable=False, comment='画像パス'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='ファイル名'),
    sa.Column('original_filename', sa.String(length=255), nullable=True, comment='元のファイル名'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True, comment='アップロード日時'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='有効フラグ'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='論理削除フラグ'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_images')
    op.drop_table('addresses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
