# -*- coding: utf-8 -*-
"""
USI to KIF Converter
USI形式の棋譜をKIF形式に変換するモジュール
python-shogiを使用して正確な局面管理と駒種判定を実行
"""

import datetime
import shogi

# 漢数字マッピング
KAN = {1:"一", 2:"二", 3:"三", 4:"四", 5:"五", 6:"六", 7:"七", 8:"八", 9:"九"}

# 駒種マッピング
PIECE = {
    shogi.PAWN: "歩", shogi.LANCE: "香", shogi.KNIGHT: "桂",
    shogi.SILVER: "銀", shogi.GOLD: "金", shogi.BISHOP: "角",
    shogi.ROOK: "飛", shogi.KING: "玉"
}

# 成り駒マッピング（KIF準拠：角/飛は馬/龍）
PROMOTED = {
    shogi.PAWN: "と", shogi.LANCE: "成香", shogi.KNIGHT: "成桂",
    shogi.SILVER: "成銀", shogi.BISHOP: "馬", shogi.ROOK: "龍"
}

# 段の文字マッピング
RANK_KAN = {"a":"一", "b":"二", "c":"三", "d":"四", "e":"五", "f":"六", "g":"七", "h":"八", "i":"九"}

def usi_sq_to_kif_sq(sq_name: str) -> str:
    """USI座標をKIF座標に変換 例: "7f" -> "七六" """
    file = int(sq_name[0])
    rank = RANK_KAN[sq_name[1]]
    return f"{KAN[file]}{rank}"

def move_to_kif_line(board: shogi.Board, move: shogi.Move, prev_to_square: int | None):
    """手をKIF形式の行に変換"""
    # 「同」判定（直前の着手と同一マス）
    to_sq_name = shogi.SQUARE_NAMES[move.to_square]  # 例: "7f"
    head = "同" if (prev_to_square is not None and prev_to_square == move.to_square) else usi_sq_to_kif_sq(to_sq_name)

    # 駒打ちの判定（from_squareがNoneまたは81以上）
    if move.from_square is None or move.from_square >= 81:
        # 駒打ち
        name = PIECE[move.drop_piece_type]
        return f"{head}{name}打"

    # 駒移動
    piece_type = board.piece_type_at(move.from_square)
    if move.promotion:
        if piece_type in (shogi.BISHOP, shogi.ROOK):
            return f"{head}{PROMOTED[piece_type]}"   # 馬 / 龍
        else:
            return f"{head}{PIECE[piece_type]}成"
    else:
        return f"{head}{PIECE[piece_type]}"

def usi_list_to_kif(moves_usi: list[str], sente="YaneuraOu NNUE", gote="人間"):
    """USI手順リストをKIF形式に変換"""
    board = shogi.Board()  # 平手初期局面
    lines = []
    prev_to = None
    
    for ply, u in enumerate(moves_usi, start=1):
        try:
            m = shogi.Move.from_usi(u)
            if m in board.legal_moves:  # 合法手チェック
                kif = move_to_kif_line(board, m, prev_to)
                lines.append(f"{ply:4d} {kif:<12} (00:00:00)")
                prev_to = m.to_square
                board.push(m)
            else:
                lines.append(f"{ply:4d} [非合法手:{u}] (00:00:00)")
        except Exception as e:
            # 無効な手の場合はスキップ
            lines.append(f"{ply:4d} [変換エラー:{u}:{e}] (00:00:00)")
    
    header = [
        "# KIF形式棋譜ファイル Generated by USI Bridge",
        f"開始日時：{datetime.date.today():%Y/%m/%d}",
        "手合割：平手",
        f"先手：{sente}",
        f"後手：{gote}",
        "手数----指手---------消費時間--",
    ]
    return "\n".join(header + lines)

class USIToKIFConverter:
    """USI棋譜をKIF形式に変換するクラス"""
    
    def __init__(self):
        pass
    
    def convert_game_to_kif(self, moves, game_info=None):
        """ゲーム情報と手順からKIF形式を生成"""
        if game_info is None:
            game_info = {}
        
        sente = game_info.get('black_player', 'YaneuraOu NNUE')
        gote = game_info.get('white_player', '人間')
        
        return usi_list_to_kif(moves, sente, gote)
    
    def usi_to_japanese_move(self, usi_move):
        """単一のUSI手をKIF形式に変換（後方互換性）"""
        try:
            board = shogi.Board()
            move = shogi.Move.from_usi(usi_move)
            return move_to_kif_line(board, move, None)
        except:
            return f"[変換エラー:{usi_move}]"

if __name__ == "__main__":
    # テスト実行
    moves = ["7g7f", "8c8d", "2g2f", "3c3d", "7i7h", "3b3c"]
    print("=== 生成されたKIF形式 ===")
    print(usi_list_to_kif(moves))
